version: '3'

services:

  nextcloud:
    image: nextcloud
    ports:
      - "8001:80"
    volumes:
      - nextcloud:/var/www/html

    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secure_password
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secure_password
    volumes:
      - db:/var/lib/mysql

volumes:
  nextcloud:
  db: