version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"
    environment:
#       PMA_ARBITRARY: 1
       PMA_HOST: mysql
       PMA_USER: root
       PMA_PASSWORD: root_password
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  wordpress_data:
  mysql_data:

