version: "3.1"
services:
    web:
      build: ./.
      container_name: mi_web
      ports: 
        - "81:80"
      volumes:
        - ./web/src/:/var/www/html
           
    db:
      image: mysql
      container_name: mi_mysql
      ports: 
        - "3307:3306" 
      restart: always
      environment:
        MYSQL_DATABASE: lamp_db
        MYSQL_USER: sergi
        MYSQL_PASSWORD: sergi
        MYSQL_ROOT_PASSWORD: sergi 

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: mi_phpmyadmin
      ports:
        - 82:80

    adminer:
      image: adminer
      container_name: mi_adminer
      ports:
        - 83:8080

